services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    command: sh -c "npm install && node backend/src/index.js"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - FRONTEND_URL=https://tfcdomain.online
      - GOOGLE_CALLBACK_URL=https://tfcdomain.online/api/auth/google/callback
    volumes:
      - ./database.sqlite:/database.sqlite
      - /tfc/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  caddy:
    build:
      context: .                   # DEBE ser la raíz
      dockerfile: caddy/Dockerfile
    container_name: caddy
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
