version: '3.8'

services:
  backend:
      build:
        context: .
        dockerfile: ./backend/Dockerfile
      ports:
        - "3000:3000"
      environment:
        - NDOE_ENV=production
        - PORT=3000
        - FRONTEND_URL=http://localhost:5173
      volumes:
        - ./database.sqlite:/app/database.sqlite
      restart: unless-stopped
      networks:
        - app-network
      command: sh -c "npm install && node backend/src/index.js"

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "80:80"
      depends_on:
        - backend
      environment:
        - VITE_API_URL=http://backend:3000
      restart: unless-stopped
      networks:
        - app-network
  
networks:
  app-network:
    driver: bridge